---
title: "Data transformation"
auteur: "Dinh-Phuc Hoang"
date: "2025-02-25"
---


```{r}
library(tidyverse)
library(dplyr)
library(DESeq2)
library(Hotelling)
library(ggplot2)
library(GGally)
library(BiocParallel)
register(SnowParam(4))
```
Data loading
```{r}
missing_values = c("C6-R-T1","P1-C-T6","P5-C-T6")
meta = read_tsv("Data FONCTIOMIC/complete_metadata_table.tsv")
meta = as.data.frame(meta)
row.names(meta) = meta$sample_id
meta <- meta[!meta$sample_id %in% missing_values,]
MGS_EC = read_rds("tb_ec_cleaned.rds")
MGS_EC = as.matrix(MGS_EC)
p2_EC = read_delim("Data FONCTIOMIC/EC_metagenome_out/pred_metagenome_unstrat.tsv.gz",delim = "\t",col_names = TRUE)
  p2_EC = as.data.frame(p2_EC)
  rownames(p2_EC) = p2_EC[,1]
  p2_EC = as.matrix(p2_EC[,-1])
overlapping_EC = intersect(rownames(p2_EC), rownames(MGS_EC))
MGS_EC = MGS_EC[overlapping_EC,colnames(MGS_EC) %in% rownames(meta)]
p2_EC = p2_EC[overlapping_EC,colnames(p2_EC) %in% rownames(meta)]
p2_EC = p2_EC[,str_sort(colnames(p2_EC),decreasing = F)]
p2_EC = p2_EC[rowSums(p2_EC) != 0 ,]
MGS_EC = MGS_EC[rowSums(MGS_EC) != 0 ,]
overlapping_EC = intersect(rownames(p2_EC), rownames(MGS_EC))
p2_EC = p2_EC[overlapping_EC,]
MGS_EC = MGS_EC[overlapping_EC,]
EC_number_class = read.table("description_mapfiles/EC_number_class.txt")
rm(missing_values, overlapping_EC)
```
Definition des variables
```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")){
  for (time in c("0","3","51","125")){
  assign(paste0(gsub(" ","_",groups),"_",time), str_sort(rownames(meta[meta$Category == groups & meta$time == time,])))
  }
}
rm(groups,time)
```
##Data transformation
1) Data transformation : DESeq2 TMM normalization
```{r}
MGS_EC = round(MGS_EC,0)
dds_MGS <- DESeqDataSetFromMatrix(countData = MGS_EC, colData = meta, design = ~  Category + time) 
dds_MGS <- estimateSizeFactors(dds_MGS)
sizeFactors(dds_MGS)
MGS_EC_norm = counts(dds_MGS, normalized=TRUE)
p2_EC = round(p2_EC,0)
dds_p2 <- DESeqDataSetFromMatrix(countData = p2_EC, colData = meta, design = ~  Category + time)
dds_p2 <- estimateSizeFactors(dds_p2)
sizeFactors(dds_p2)
p2_EC_norm = counts(dds_p2, normalized=TRUE)
```

```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("mat_", gsub(" ", "_", groups), "_", time), MGS_EC_norm[, get(paste0(gsub(" ", "_", groups), "_", time))])
  }
}
```

```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("P2_mat_", gsub(" ", "_", groups), "_", time), p2_EC_norm[, get(paste0(gsub(" ", "_", groups), "_", time))])
  }
}
```

```{r}
for (groups in c("Control_Cropland","Amended_Cropland","Control_Grassland","Amended_Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("cor_", groups, "_", time), 
            cor(t(get(paste0("mat_", groups, "_", time))), t(get(paste0("P2_mat_", groups, "_", time))), method = "spearman"))
    assign(paste0("d_cor_", groups, "_", time), 
            diag(get(paste0("cor_", groups, "_", time))))
        assign(paste0("corr_", groups, "_", time), 
            cor.test(t(get(paste0("mat_", groups, "_", time))), t(get(paste0("P2_mat_", groups, "_", time))), method = "spearman"))

  }
}
```
2) CLR transformation
```{r}
MGS_EC_clr = clr(MGS_EC)
p2_EC_clr = clr(p2_EC)
rm(list = c("MGS_EC_norm","p2_EC_norm"))
MGS_EC_clr = MGS_EC_clr[rowSums(is.na(MGS_EC_clr)) == 0,]
p2_EC_clr = p2_EC_clr[rowSums(is.na(p2_EC_clr)) == 0,]
c =intersect(rownames(MGS_EC_clr),rownames(p2_EC_clr))
MGS_EC_clr = MGS_EC_clr[c,]
p2_EC_clr = p2_EC_clr[c,]
rm(c)
```

```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("mat_", gsub(" ", "_", groups), "_", time), MGS_EC_clr[, get(paste0(gsub(" ", "_", groups), "_", time))])
  }
}
```

```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("P2_mat_", gsub(" ", "_", groups), "_", time), p2_EC_clr[, get(paste0(gsub(" ", "_", groups), "_", time))])
  }
}
```

```{r}
for (groups in c("Control_Cropland","Amended_Cropland","Control_Grassland","Amended_Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("cor_", groups, "_", time), 
            cor(t(get(paste0("mat_", groups, "_", time))), t(get(paste0("P2_mat_", groups, "_", time))), method = "spearman"))
    assign(paste0("d_cor_", groups, "_", time), 
            diag(get(paste0("cor_", groups, "_", time))))
        assign(paste0("corr_", groups, "_", time), 
            cor.test(t(get(paste0("mat_", groups, "_", time))), t(get(paste0("P2_mat_", groups, "_", time))), method = "spearman"))

  }
}
```

3) Imputation des valeurs nulles + transformation CLR
```{r}
MGS_EC_imp = MGS_EC
MGS_EC_imp[MGS_EC_imp == 0] <- 0.01
MGS_EC_imp = clr(MGS_EC_imp)
p2_EC_imp = p2_EC
p2_EC_imp[p2_EC_imp == 0] <- 0.01
p2_EC_imp = clr(p2_EC_imp)
```

```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("mat_", gsub(" ", "_", groups), "_", time), MGS_EC_imp[, get(paste0(gsub(" ", "_", groups), "_", time))])
  }
}
```

```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("P2_mat_", gsub(" ", "_", groups), "_", time), p2_EC_imp[, get(paste0(gsub(" ", "_", groups), "_", time))])
  }
}
```

```{r}
for (groups in c("Control_Cropland","Amended_Cropland","Control_Grassland","Amended_Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("cor_", groups, "_", time), 
            cor(t(get(paste0("mat_", groups, "_", time))), t(get(paste0("P2_mat_", groups, "_", time))), method = "spearman"))
    assign(paste0("d_cor_", groups, "_", time), 
            diag(get(paste0("cor_", groups, "_", time))))
        assign(paste0("corr_", groups, "_", time), 
            cor.test(t(get(paste0("mat_", groups, "_", time))), t(get(paste0("P2_mat_", groups, "_", time))), method = "spearman"))

  }
}
```
Regroupement des abondances ECs en fonction des conditions
```{r}
control_0 = c(Control_Cropland_0,Control_Grassland_0)
control_3 = c(Control_Cropland_3,Control_Grassland_3)
control_51 = c(Control_Cropland_51,Control_Grassland_51)
control_125 = c(Control_Cropland_125,Control_Grassland_125)
amended_0 = c(Amended_Cropland_0,Amended_Grassland_0)
amended_3 = c(Amended_Cropland_3,Amended_Grassland_3)
amended_51 = c(Amended_Cropland_51,Amended_Grassland_51)
amended_125 = c(Amended_Cropland_125,Amended_Grassland_125)
```

```{r}
for (groups in c("control","amended")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("mat_", groups, "_", time), MGS_EC[, get(paste0(groups, "_", time))])
  }
}
```

```{r}
for (groups in c("control","amended")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("P2_mat_", groups, "_", time), p2_EC[, get(paste0(groups, "_", time))])
  }
}
```

```{r}
for (groups in c("control","amended")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("cor_", groups, "_", time), 
            cor(t(get(paste0("mat_", groups, "_", time))), t(get(paste0("P2_mat_", groups, "_", time))), method = "spearman"))
    assign(paste0("d_cor_", groups, "_", time), 
            diag(get(paste0("cor_", groups, "_", time))))
        assign(paste0("corr_", groups, "_", time), 
            cor.test(t(get(paste0("mat_", groups, "_", time))), t(get(paste0("P2_mat_", groups, "_", time))), method = "spearman"))

  }
}
```
Test de normalité
```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("mat_", gsub(" ", "_", groups), "_", time), MGS_EC[, get(paste0(gsub(" ", "_", groups), "_", time))])
  }
}
```

```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("P2_mat_", gsub(" ", "_", groups), "_", time), p2_EC[, get(paste0(gsub(" ", "_", groups), "_", time))])
  }
}
```

```{r}
ggpairs(mat_control_0,upper=list(continuous=wrap(ggally_cor,method = "spearman")))
ggpairs(P2_mat_control_0,upper=list(continuous=wrap(ggally_cor,method = "spearman")))
```

```{r}
CC0_MGSvsP2 = cbind(mat_Control_Cropland_0,P2_mat_Control_Cropland_0)
colnames(CC0_MGSvsP2) = c(paste0("MGS_",colnames(mat_Control_Cropland_0)),paste0("P2_",colnames(P2_mat_Control_Cropland_0)))
ggpairs(CC0_MGSvsP2,upper=list(continuous=wrap(ggally_cor,method = "spearman")))
```

```{r}
AG51_MGSvsP2 = cbind(mat_Amended_Grassland_51,P2_mat_Amended_Grassland_51)
colnames(AG51_MGSvsP2) = c(paste0("MGS_",colnames(mat_Amended_Grassland_51)),paste0("P2_",colnames(P2_mat_Amended_Grassland_51)))
ggpairs(AG51_MGSvsP2,upper=list(continuous=wrap(ggally_cor,method = "spearman")))
```

```{r}
control0_MGSvsP2 = cbind(mat_control_0,P2_mat_control_0)
colnames(control0_MGSvsP2) = c(paste0("MGS_",colnames(mat_control_0)),paste0("P2_",colnames(P2_mat_control_0)))
ggpairs(control0_MGSvsP2,upper=list(continuous=wrap(ggally_cor,method = "spearman")))
```

```{r}
scatter_data <- data.frame(x = as.vector(MGS_EC), y = as.vector(p2_EC))
scatter_data$EC_number = rep(rownames(MGS_EC), ncol(MGS_EC))
scatter_data = left_join(scatter_data, EC_number_class, by = "EC_number")
scatter_data$EC_class = as.factor(scatter_data$EC_class)
ec_colors <- c("Hydrolases" = "#E41A1C",  # Red
  "Isomerases" = "#377EB8",  # Blue
  "Ligases" = "#4DAF4A",  # Green
  "Lyases" = "#984EA3",  # Purple
  "Oxidoreductases" = "#FF7F00",  # Orange
  "Transferases" = "#A65628")  # Yellow)
ggplot(scatter_data, aes(x = x, y = y, color = EC_class)) +
  geom_point(size = 2, alpha = 0.8) +  # Adjust point size and transparency
  labs(x = "MGS EC Abundance", y = "P2 EC Abundance", title = "MGS vs P2 Comparison by EC Class") +
  scale_color_manual(values = ec_colors) +  # Apply the custom color palette
  theme_minimal() +
  theme(
plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10))
```

```{r}
for (groups in c("Control_Cropland","Amended_Grassland")) {
  for (time in c("0","3","51","125")) {
     mat_MGS <- get(paste0("mat_", groups, "_", time))
    mat_P2 <- get(paste0("P2_mat_", groups, "_", time))
    scatter_data_temp <- data.frame(
      x = as.vector(mat_MGS),
      y = as.vector(mat_P2),
      EC_number = rep(rownames(mat_MGS), ncol(mat_MGS))
    )
    scatter_data_temp <- left_join(scatter_data_temp, EC_number_class, by = "EC_number")
    scatter_data_temp$EC_class <- as.factor(scatter_data_temp$EC_class)
    ec_colors <- c("Hydrolases" = "#E41A1C",  # Red
      "Isomerases" = "#377EB8",  # Blue
      "Ligases" = "#4DAF4A",  # Green
      "Lyases" = "#984EA3",  # Purple
      "Oxidoreductases" = "#FF7F00",  # Orange
      "Transferases" = "#A65628")  # Yellow)

     tmp <- ggplot(scatter_data_temp, aes(x = x, y = y, color = EC_class)) +
        geom_point(size = 2, alpha = 0.8) +  # Adjust point size and transparency
        labs(x = "MGS", y = "P2", title = paste("MGS vs P2 Comparison-", groups, time)) +
        scale_color_manual(values = ec_colors) +  # Apply the custom color palette
        theme_minimal() +
        theme(
        plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10))
      
      assign(paste0("splot_", groups, "_", time), tmp)
  }}

```