---
title: "Data transformation"
auteur: "Dinh-Phuc Hoang"
date: "2025-02-25"
---


```{r}
library(tidyverse)
library(dplyr)
library(DESeq2)
library(Hotelling)
library(BiocParallel)
register(SnowParam(4))
```
Data loading
```{r}
meta = read_tsv("Data FONCTIOMIC/complete_metadata_table.tsv")
meta = as.data.frame(meta)
row.names(meta) = meta$sample_id
MGS_EC = read_rds("tb_ec_cleaned.rds")
p2_EC = read_rds("Data FONCTIOMIC/picrust2out_ver2/p2_EC.rds")
overlapping_EC = intersect(rownames(p2_EC), rownames(MGS_EC))
MGS_EC = MGS_EC[,colnames(MGS_EC) %in% rownames(meta)]
p2_EC = p2_EC[,colnames(p2_EC) %in% rownames(meta)]
p2_EC = p2_EC[,str_sort(colnames(p2_EC),decreasing = F)]
#p2_EC = p2_EC[rowMeans(p2_EC == 0) < 0.9 ,]
#MGS_EC = MGS_EC[rowMeans(p2_EC == 0) < 0.9 ,]
EC_number_class = read.table("description_mapfiles/EC_number_class.txt")
COG_anno =  read_rds("description_mapfiles/COG_anno.rds")
p2_COG = read_rds("Data FONCTIOMIC/picrust2out_ver2/p2_COG.rds")
p2_COG = p2_COG[,str_sort(colnames(p2_COG),decreasing = F)]
p2_COG = p2_COG[,rownames(meta)]
MGS_COG = read_tsv("Data FONCTIOMIC/counts_by_COG.raw.tsv")
MGS_COG = as.data.frame(MGS_COG)
  rownames(MGS_COG) = MGS_COG[,1]
  MGS_COG = MGS_COG[,-1]
rm(overlapping_EC)
```
Data transformation : DESeq2 TMM normalization
```{r}
MGS_EC = round(MGS_EC,0)
dds_MGS <- DESeqDataSetFromMatrix(countData = MGS_EC, colData = meta, design = ~  Category + time) 
dds_MGS <- estimateSizeFactors(dds_MGS)
sizeFactors(dds_MGS)
MGS_EC_norm = counts(dds_MGS, normalized=TRUE)
p2_EC = round(p2_EC,0)
dds_p2 <- DESeqDataSetFromMatrix(countData = p2_EC, colData = meta, design = ~  Category + time)
dds_p2 <- estimateSizeFactors(dds_p2)
sizeFactors(dds_p2)
p2_EC_norm = counts(dds_p2, normalized=TRUE)
```
CLR transformation
```{r}
MGS_EC_norm = MGS_EC
p2_EC_norm = p2_EC
MGS_EC_clr = clr(MGS_EC_norm)
p2_EC_clr = clr(p2_EC_norm)
rm(list = c("MGS_EC_norm","p2_EC_norm"))
MGS_EC_clr = MGS_EC_clr[rowSums(is.na(MGS_EC_clr)) == 0,]
p2_EC_clr = p2_EC_clr[rowSums(is.na(p2_EC_clr)) == 0,]
c =intersect(rownames(MGS_EC_clr),rownames(p2_EC_clr))
MGS_EC_clr = MGS_EC_clr[c,]
p2_EC_clr = p2_EC_clr[c,]
rm(c)
```

```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")){
  for (time in c("0","3","51","125")){
  assign(paste0(gsub(" ","_",groups),"_",time), str_sort(rownames(meta[meta$Category == groups & meta$time == time,])))
  }
}
rm(groups,time)
```

```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("mat_", gsub(" ", "_", groups), "_", time), MGS_EC_norm[, get(paste0(gsub(" ", "_", groups), "_", time))])
  }
}
```

```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("P2_mat_", gsub(" ", "_", groups), "_", time), p2_EC_norm[, get(paste0(gsub(" ", "_", groups), "_", time))])
  }
}
```

```{r}
#Cropland
dif_C_0 = mat_Control_Cropland_0 - mat_Amended_Cropland_0
#dif_C_3 = mat_Control_Cropland_3 - mat_Amended_Cropland_3
dif_C_51 = mat_Control_Cropland_51 - mat_Amended_Cropland_51
dif_C_125 = mat_Control_Cropland_125 - mat_Amended_Cropland_125
#Grassland
dif_G_0 = mat_Control_Grassland_0 - mat_Amended_Grassland_0
dif_G_3 = mat_Control_Grassland_3 - mat_Amended_Grassland_3
dif_G_51 = mat_Control_Grassland_51 - mat_Amended_Grassland_51
#dif_G_125 = mat_Control_Grassland_125 - mat_Amended_Grassland_125
```

```{r}
#Cropland
P2_dif_C_0 = P2_mat_Control_Cropland_0 - P2_mat_Amended_Cropland_0
#P2_dif_C_3 = P2_mat_Control_Cropland_3 - P2_mat_Amended_Cropland_3 #Error: missing value C6-R-T1
P2_dif_C_51 = P2_mat_Control_Cropland_51 - P2_mat_Amended_Cropland_51
P2_dif_C_125 = P2_mat_Control_Cropland_125 - P2_mat_Amended_Cropland_125
#Grassland
P2_dif_G_0 = P2_mat_Control_Grassland_0 - P2_mat_Amended_Grassland_0
P2_dif_G_3 = P2_mat_Control_Grassland_3 - P2_mat_Amended_Grassland_3
P2_dif_G_51 = P2_mat_Control_Grassland_51 - P2_mat_Amended_Grassland_51
#P2_dif_G_125 = P2_mat_Control_Grassland_125 - P2_mat_Amended_Grassland_125 #Error: missing value P1_C_T6 & P5-C-T6
```

```{r}
DA_EC_MGS_Crops <- read_rds("Output/DA_EC_MGS_Crops.rds")
DA_EC_MGS_Grass <- read_rds("Output/DA_EC_MGS_Grass.rds")
DA_EC_P2_Crops <- read_rds("Output/DA_EC_P2_Crops.rds")
DA_EC_P2_Grass <- read_rds("Output/DA_EC_P2_Grass.rds") 
```

```{r}
DA_EC_MGS_Crop = unique(intersect(DA_EC_MGS_Crops$EC_number,DA_EC_P2_Crops$EC_number))
EC_dif_MGS = MGS_EC %>% as.data.frame() %>%
  rownames_to_column("EC_number") %>%
  filter(EC_number %in% DA_EC_MGS_Crop)
rownames(EC_dif_MGS) = EC_dif_MGS$EC_number
EC_dif_MGS = EC_dif_MGS[,-1]
EC_dif_MGS = t(EC_dif_MGS)
EC_dif_MGS = EC_dif_MGS %>% as.data.frame() %>% rownames_to_column("sample_id") %>% left_join(meta[,c("sample_id","Category","time")], by = "sample_id") %>% 
column_to_rownames("sample_id")
EC_dif_MGS$Category = as.factor(EC_dif_MGS$Category)
EC_dif_MGS$time = as.factor(EC_dif_MGS$time)
EC_dif_MGS = EC_dif_MGS %>% filter(Category != "Control Grassland" & Category != "Amended Grassland") %>% arrange(Category,time)
plot_ec1 = ggplot( EC_dif_MGS, aes(x = time, y=as.numeric(`EC:1.1.5.8`), fill = Category ) ) +
  geom_boxplot() +
  scale_fill_manual(values = c("Amended Cropland"="#fbbb3f", "Control Cropland"="#f2e0bd",
                                  "Amended Grassland"="#2abf2a", "Control Grassland"="#b2d9b2"),
                      labels = c("Amended Cropland"='Amended Crops', "Control Cropland"='Control Crops', 
                                  "Amended Grassland"='Amended Grassland', "Control Grassland"='Control Grassland'))+
  labs(title = "Relative abundance of EC:1.1.5.8 (MGS)") +
  ylab(NULL)+
  xlab (NULL) +
  guides(fill = FALSE) +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
plot_ec2 = ggplot( EC_dif_MGS, aes(x = time, y=as.numeric(`EC:1.1.9.1`), fill = Category ) ) +
  geom_boxplot() +
  scale_fill_manual(values = c("Amended Cropland"="#fbbb3f", "Control Cropland"="#f2e0bd",
                                  "Amended Grassland"="#2abf2a", "Control Grassland"="#b2d9b2"),
                      labels = c("Amended Cropland"='Amended Crops', "Control Cropland"='Control Crops', 
                                  "Amended Grassland"='Amended Grassland', "Control Grassland"='Control Grassland'))+
  labs(title = "Relative abundance of EC:1.1.9.1 (MGS)") +
  ylab(NULL)+
  xlab (NULL) +
  guides(fill = FALSE) +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
plot_ec3 = ggplot( EC_dif_MGS, aes(x = time, y=as.numeric(`EC:1.14.12.17`), fill = Category ) ) +
  geom_boxplot() +
  scale_fill_manual(values = c("Amended Cropland"="#fbbb3f", "Control Cropland"="#f2e0bd",
                                  "Amended Grassland"="#2abf2a", "Control Grassland"="#b2d9b2"),
                      labels = c("Amended Cropland"='Amended Crops', "Control Cropland"='Control Crops', 
                                  "Amended Grassland"='Amended Grassland', "Control Grassland"='Control Grassland'))+
  labs(title = "Relative abundance of EC:1.14.12.17 (MGS)") +
  ylab(NULL)+
  xlab (NULL) +
  guides(fill = FALSE) +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
plot_ec4 = ggplot( EC_dif_MGS, aes(x = time, y=as.numeric(`EC:1.4.1.2`), fill = Category ) ) +
  geom_boxplot() +
  scale_fill_manual(values = c("Amended Cropland"="#fbbb3f", "Control Cropland"="#f2e0bd",
                                  "Amended Grassland"="#2abf2a", "Control Grassland"="#b2d9b2"),
                      labels = c("Amended Cropland"='Amended Crops', "Control Cropland"='Control Crops', 
                                  "Amended Grassland"='Amended Grassland', "Control Grassland"='Control Grassland'))+
  labs(title = "Relative abundance of EC:1.4.1.2 (MGS)") +
  ylab(NULL)+
  xlab (NULL) +
  guides(fill = FALSE) +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
plot_grid_EC_MGS_Crop <- ggarrange(plot_ec1, plot_ec2, plot_ec3, plot_ec4, ncol = 2, nrow = 2, common.legend = TRUE, legend = "bottom")
plot_grid_EC_MGS_Crop <- annotate_figure(plot_grid_EC_MGS_Crop, top = text_grob("The abundance of ECs noted by test DAG between control and amended sample from Cropland (MGS)", face = "bold", size = 14))
ggsave("Output/plot_grid_EC_MGS_Crop.png", plot = plot_grid_EC_MGS_Crop, width = 12, height = 8, dpi = 300)
ggsave("Output/EC1158.png", plot = plot_ec1, width = 10, height = 8, dpi = 300)
ggsave("Output/EC1191.png", plot = plot_ec2, width = 10, height = 8, dpi = 300)
ggsave("Output/EC1141217.png", plot = plot_ec3, width = 10, height = 8, dpi = 300)
ggsave("Output/EC1412.png", plot = plot_ec4, width = 10, height = 8, dpi = 300)
```

```{r}
EC_dif_P2 = p2_EC %>% as.data.frame() %>%
  rownames_to_column("EC_number") %>%
  filter(EC_number %in% DA_EC_Crop)
rownames(EC_dif_P2) = EC_dif_P2$EC_number
EC_dif_P2 = EC_dif_P2[,-1]
EC_dif_P2 = t(EC_dif_P2)
EC_dif_P2 = EC_dif_P2 %>% as.data.frame() %>% rownames_to_column("sample_id") %>% left_join(meta[,c("sample_id","Category","time")], by = "sample_id") %>% 
column_to_rownames("sample_id")
EC_dif_P2$Category = as.factor(EC_dif_P2$Category)
EC_dif_P2$time = as.factor(EC_dif_P2$time)
EC_dif_P2 = EC_dif_P2 %>% filter(Category != "Control Grassland" & Category != "Amended Grassland") %>% arrange(Category,time)
plot_ec1 = ggplot( EC_dif_P2, aes(x = time, y=as.numeric(`EC:1.1.5.8`), fill = Category ) ) +
  geom_boxplot() +
  scale_fill_manual(values = c("Amended Cropland"="#fbbb3f", "Control Cropland"="#f2e0bd",
                                  "Amended Grassland"="#2abf2a", "Control Grassland"="#b2d9b2"),
                      labels = c("Amended Cropland"='Amended Crops', "Control Cropland"='Control Crops', 
                                  "Amended Grassland"='Amended Grassland', "Control Grassland"='Control Grassland'))+
  labs(title = "Relative abundance of EC:1.1.5.8 (P2)") +
  ylab(NULL)+
  xlab (NULL) +
  guides(fill = FALSE) +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
plot_ec2 = ggplot( EC_dif_P2, aes(x = time, y=as.numeric(`EC:1.1.9.1`), fill = Category ) ) +
  geom_boxplot() +
  scale_fill_manual(values = c("Amended Cropland"="#fbbb3f", "Control Cropland"="#f2e0bd",
                                  "Amended Grassland"="#2abf2a", "Control Grassland"="#b2d9b2"),
                      labels = c("Amended Cropland"='Amended Crops', "Control Cropland"='Control Crops', 
                                  "Amended Grassland"='Amended Grassland', "Control Grassland"='Control Grassland'))+
  labs(title = "Relative abundance of EC:1.1.9.1 (P2)") +
  ylab(NULL)+
  xlab (NULL) +
  guides(fill = FALSE) +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
plot_ec3 = ggplot( EC_dif_P2, aes(x = time, y=as.numeric(`EC:1.14.12.17`), fill = Category ) ) +
  geom_boxplot() +
  scale_fill_manual(values = c("Amended Cropland"="#fbbb3f", "Control Cropland"="#f2e0bd",
                                  "Amended Grassland"="#2abf2a", "Control Grassland"="#b2d9b2"),
                      labels = c("Amended Cropland"='Amended Crops', "Control Cropland"='Control Crops', 
                                  "Amended Grassland"='Amended Grassland', "Control Grassland"='Control Grassland'))+
  labs(title = "Relative abundance of EC:1.14.12.17 (P2)") +
 ylab(NULL)+
  xlab (NULL) +
  guides(fill = FALSE) +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
plot_ec4 = ggplot( EC_dif_P2, aes(x = time, y=as.numeric(`EC:1.4.1.2`), fill = Category ) ) +
  geom_boxplot() +
  scale_fill_manual(values = c("Amended Cropland"="#fbbb3f", "Control Cropland"="#f2e0bd",
                                  "Amended Grassland"="#2abf2a", "Control Grassland"="#b2d9b2"),
                      labels = c("Amended Cropland"='Amended Crops', "Control Cropland"='Control Crops', 
                                  "Amended Grassland"='Amended Grassland', "Control Grassland"='Control Grassland'))+
  labs(title = "Relative abundance of EC:1.4.1.2 (P2)") +
  ylab(NULL)+
  xlab (NULL) +
  guides(fill = FALSE) +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
plot_grid_EC_P2_Crop <- ggarrange(plot_ec1, plot_ec2, plot_ec3, plot_ec4, ncol = 2, nrow = 2, common.legend = TRUE, legend = "bottom")
plot_grid_EC_P2_Crop <- annotate_figure(plot_grid_EC_P2_Crop, top = text_grob("The abundance of ECs noted by test DAG between control and amended sample from Cropland (PICRUSt2)", face = "bold", size = 14))
ggsave("Output/plot_grid_EC_P2_Crop.png", plot = plot_grid_EC_P2_Crop, width = 12, height = 8, dpi = 300)
ggsave("Output/EC1158_P2.png", plot = plot_ec1, width = 10, height = 8, dpi = 300)
ggsave("Output/EC1191_P2.png", plot = plot_ec2, width = 10, height = 8, dpi = 300)
ggsave("Output/EC1141217_P2.png", plot = plot_ec3, width = 10, height = 8, dpi = 300)
ggsave("Output/EC1412_P2.png", plot = plot_ec4, width = 10, height = 8, dpi = 300)
```

```{r}
DA_COG_MGS_Crop = read_rds("Output/DA_COG_MGS_Crops.rds")
DA_COG_MGS_Grass = read_rds("Output/DA_COG_MGS_Grass.rds")
DA_COG_P2_Crop = read_rds("Output/DA_COG_P2_Crops.rds")
DA_COG_P2_Grass = read_rds("Output/DA_COG_P2_Grass.rds")
```

```{r}
DA_COG_MGS = unique(c(DA_COG_MGS_Crop$COG_number,DA_COG_MGS_Grass$COG_number))
DA_COG_P2 = unique(c(DA_COG_P2_Crop$COG_number,DA_COG_P2_Grass$COG_number))
DA_COG_commun = intersect(DA_COG_MGS,DA_COG_P2)
df_DA_COG_MGS = rbind(DA_COG_MGS_Crop,DA_COG_MGS_Grass)
df_DA_COG_MGS = df_DA_COG_MGS[df_DA_COG_MGS$COG_number %in% DA_COG_commun,]
```

```{r}
venn.diagram(
        x = list(rownames(count_COG_MGS), rownames(count_COG_P2)),
        category.names = c("MGS" , "PICRUSt2"),
        filename = 'Output/#venn_diagramm_COG.png',
        output=TRUE,
        imagetype="png" ,
        lwd = 2,
        lty = 'blank',
        fill = c("cornflowerblue", "pink"),
        cat.fontface = "bold",
        cat.default.pos = "outer",
        cat.fontfamily = "sans",
)
```
```{r}
overlapping_COG = intersect(rownames(MGS_COG), rownames(p2_COG))
count_COG_MGS = MGS_COG[DA_COG_commun,meta$sample_id]
count_COG_P2 = p2_COG[DA_COG_commun,meta$sample_id]
rm(overlapping_COG)
```
Definition des variables
```{r}
for (groups in c("Control Cropland","Amended Cropland","Control Grassland","Amended Grassland")){
  for (time in c("0","3","51","125")){
  assign(paste0(gsub(" ","_",groups),"_",time), str_sort(rownames(meta[meta$Category == groups & meta$time == time,])))
  }
}
rm(groups,time)
```
Regroupement des abondances ECs en fonction des conditions
```{r}
crop_0 = c(Control_Cropland_0,Amended_Cropland_0)
crop_3 = c(Control_Cropland_3,Amended_Cropland_3)
crop_51 = c(Control_Cropland_51,Amended_Cropland_51)
crop_125 = c(Control_Cropland_125,Amended_Cropland_125)
grass_0 = c(Control_Grassland_0,Amended_Grassland_0)
grass_3 = c(Control_Grassland_3,Amended_Grassland_3)
grass_51 = c(Control_Grassland_51,Amended_Grassland_51)
grass_125 = c(Control_Grassland_125,Amended_Grassland_125)
```
```{r}
for (groups in c("crop","grass")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("mat_", groups, "_", time), count_COG_MGS[, get(paste0(groups, "_", time))])
  }
}
```
```{r}
for (groups in c("crop","grass")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("P2_mat_", groups, "_", time), count_COG_P2[, get(paste0(groups, "_", time))])
  }
}
```
```{r}
for (groups in c("crop","grass")) {
  for (time in c("0","3","51","125")) {
    assign(paste0("cor_", groups, "_", time), 
            cor(t(get(paste0("mat_", groups, "_", time))), t(get(paste0("P2_mat_", groups, "_", time))), method = "spearman"))
    assign(paste0("d_cor_", groups, "_", time), 
            diag(get(paste0("cor_", groups, "_", time))))
        assign(paste0("corr_", groups, "_", time), 
            cor.test(t(get(paste0("mat_", groups, "_", time))), t(get(paste0("P2_mat_", groups, "_", time))), method = "spearman"))
  }
}
```

```{r}
MGS_COG_vst = round(MGS_COG,0)
dds_MGS_COG <- DESeqDataSetFromMatrix(countData = MGS_COG_vst,
                                  colData = meta,
                                  design = ~ Category + time, tidy = FALSE)
vst_COG_MGS = vst(dds_MGS_COG,blind = FALSE)
count_COG_MGS = assay(vst_COG_MGS)
p2_COG_vst = round(p2_COG,0)
dds_p2_COG <- DESeqDataSetFromMatrix(countData = p2_COG_vst,
                                  colData = meta,
                                  design = ~ Category + time, tidy = FALSE)
vst_COG_P2 = vst(dds_p2_COG,blind = FALSE)
count_COG_P2 = assay(vst_COG_P2)
```

```{r}
COG_anno$annotation = paste0(COG_anno$COG_letter,":[",COG_anno$COG_category,"]")
COG_anno$COG = rownames(COG_anno)
cog_color = c("J"="#ff0000", 
"A:" = "#c2af58", "K" = "#ff9900", 
"L" = "#ffff00", "B" = "#ffc600", 
"D" = "#99ff00", 
"Y" = "#ff008a", 
"T" = "#0000ff", "M" = "#9ec928", 
"N" = "#006633", "Z" = "#660099", 
"W" = "#336699", "U" = "#33cc99", 
"O" = "#00ffff", 
"X" = "#9900ff", "C" = "#805642", 
"G" = "#ff00ff", "E" = "#99334d", 
"F" = "#727dcc", "H" = "#5c5a1b", 
"I" = "#0099ff", "P" = "#ffcc99", 
"Q" = "#ff9999", 
"R" = "#d6aadf", "S" = "#FFFFFF")
plot_cor = list()
for (groups in c("crop","grass")) {
  for (time in c("0","3","51","125")) {
    d_cor = as.data.frame(get(paste0("d_cor_", groups, "_", time)))
    names(d_cor) = c("coeff")
    d_cor$COG = rownames(d_cor)
    d_cor = merge(d_cor, COG_anno[,c(1,5)], by = "COG")
    plot_cor[[paste0(groups, "_", time)]] = ggplot(d_cor, aes(x = coeff, y = COG_letter, group = COG_letter, color = COG_letter, fill = COG_letter)) +
      geom_boxplot(alpha=0.5,show.legend = FALSE)+
      geom_jitter(color="black", size=0.4, alpha=0.9,show.legend = FALSE)+
      geom_vline(xintercept = 0, linetype="dotted", 
                color = "#000000", linewidth=0.7)+
      scale_fill_manual(values = cog_color) +
      scale_color_manual(values = cog_color) +
      ggtitle(paste("Correlation of Spearman on group", groups, time)) +
      xlab("Spearman correlation") +
      ylab("COG")+
      theme_classic()
  }
}
plot_grid_Crop <- ggarrange(plot_cor$crop_0, plot_cor$crop_3, plot_cor$crop_51, plot_cor$crop_125,
                            ncol = 2, nrow = 2)
plot_grid_Grass <- ggarrange(plot_cor$grass_0, plot_cor$grass_3, plot_cor$grass_51, plot_cor$grass_125,
                            ncol = 2, nrow = 2)
ggsave(plot = plot_grid_Crop, filename = "Output/boxplot_cor_spearman_Crop_COG.png", width = 20, height = 30, dpi = 300)
ggsave(plot = plot_grid_Grass, filename = "Output/boxplot_cor_spearman_Grass_COG.png", width = 20, height = 30, dpi = 300)

```

 ```{r}
COG_anno$COG = rownames(COG_anno)
COG_anno$annotation = paste0(COG_anno$COG_letter,":[",COG_anno$COG_category,"]")
count_COG_MGS = as.data.frame(count_COG_MGS)
count_COG_P2 = as.data.frame(count_COG_P2)
count_COG_MGS$COG = rownames(count_COG_MGS)
count_COG_MGS = count_COG_MGS %>% left_join(COG_anno[,c(4,5)], by = "COG")
count_COG_P2$COG = rownames(count_COG_P2)
count_COG_P2 = count_COG_P2 %>% left_join(COG_anno[,c(4,5)], by = "COG")
```

```{r}
count_COG_MGS = count_COG_MGS %>% pivot_longer(cols = -c(COG, annotation), names_to = "sample", values_to = "counts")
count_COG_P2 = count_COG_P2 %>% pivot_longer(cols = -c(COG, annotation), names_to = "sample", values_to = "counts")
```

```{r}
count_COG_MGS = count_COG_MGS[count_COG_MGS$sample %in% c("C1-C-T0", "C3-C-T0", "C5-C-T0","P1-C-T0", "P3-C-T0", "P5-C-T0"),]
aggregate(count_COG_MGS$counts, by = list(COG_anno = count_COG_MGS$annotation,
                                          sample = count_COG_MGS$sample), FUN = sum) -> count_COG_MGS
count_COG_MGS$COG_counts = count_COG_MGS$x
for (samp in c ("C1-C-T0", "C3-C-T0", "C5-C-T0","P1-C-T0", "P3-C-T0", "P5-C-T0")){
  count_COG_MGS[count_COG_MGS$sample  == samp,"total_sample"] = sum(count_COG_MGS[count_COG_MGS$sample == samp,"COG_counts"])
}
count_COG_MGS$per_counts = (count_COG_MGS$COG_counts / count_COG_MGS$total_sample*100)
count_COG_MGS$method = "MGS"
```

```{r}
count_COG_P2 = count_COG_P2[count_COG_P2$sample %in% c("C1-C-T0", "C3-C-T0", "C5-C-T0","P1-C-T0", "P3-C-T0", "P5-C-T0"),]
aggregate(count_COG_P2$counts, by = list(COG_anno = count_COG_P2$annotation,
                                          sample = count_COG_P2$sample), FUN = sum) -> count_COG_P2
count_COG_P2$COG_counts = count_COG_P2$x
for (samp in c ("C1-C-T0", "C3-C-T0", "C5-C-T0","P1-C-T0", "P3-C-T0", "P5-C-T0")){
  count_COG_P2[count_COG_P2$sample  == samp,"total_sample"] = sum(count_COG_P2[count_COG_P2$sample == samp,"COG_counts"])
}
count_COG_P2$per_counts = (count_COG_P2$COG_counts / count_COG_P2$total_sample*100)
count_COG_P2$method = "P2"
```

```{r}
data_df = rbind(count_COG_MGS, count_COG_P2)
data_df$COG_anno = as.factor(data_df$COG_anno)
data_df$method = as.factor(data_df$method)
data_df$sample = as.character(data_df$sample)
keep_COG = data_df[data_df$per_counts > 1,"COG_anno"]
data_df[startsWith(data_df$sample, "C"), "land_use"] <- "cropland"
data_df[startsWith(data_df$sample, "P"), "land_use"] <- "grassland"
test_data_df = data_df[data_df$COG_anno %in% keep_COG,]
#color for COG and strips
col_COG = c("J:[Translation, ribosomal structure and biogenesis]" = "#ff0000", 
"A:[RNA processing and modification]" = "#c2af58", "K:[Transcription]" = "#ff9900", 
"L:[Replication, recombination and repair]" = "#ffff00", "B:[Chromatin structure and dynamics]" = "#ffc600", 
"D:[Cell cycle control, cell division, chromosome partitioning]" = "#99ff00", 
"Y:[Nuclear structure]" = "#493126", "V:[Defense mechanisms]" = "#ff008a", 
"T:[Signal transduction mechanisms]" = "#0000ff", "M:[Cell wall/membrane/envelope biogenesis]" = "#9ec928", 
"N:[Cell motility]" = "#006633", "Z:[Cytoskeleton]" = "#660099", 
"W:[Extracellular structures]" = "#336699", "U:[Intracellular trafficking, secretion, and vesicular transport]" = "#33cc99", 
"O:[Posttranslational modification, protein turnover, chaperones]" = "#00ffff", 
"X:[Mobilome: prophages, transposons]" = "#9900ff", "C:[Energy production and conversion]" = "#805642", 
"G:[Carbohydrate transport and metabolism]" = "#ff00ff", "E:[Amino acid transport and metabolism]" = "#99334d", 
"F:[Nucleotide transport and metabolism]" = "#727dcc", "H:[Coenzyme transport and metabolism]" = "#5c5a1b", 
"I:[Lipid transport and metabolism]" = "#0099ff", "P:[Inorganic ion transport and metabolism]" = "#ffcc99", 
"Q:[Secondary metabolites biosynthesis, transport and catabolism]" = "#ff9999", 
"R:[General function prediction only]" = "#d6aadf", "S:[Function unknown]" = "#FFFFFF")

scales <- list(scale_x_discrete(labels=c("C1.C.T0", "C3.C.T0", "C5.C.T0")),
               scale_x_discrete(labels=c("P1-C-T0", "P3-C-T0", "P5-C-T0")),
               scale_x_discrete(labels=c("C1.C.T0", "C3.C.T0", "C5.C.T0")),
               scale_x_discrete(labels=c("P1-C-T0", "P3-C-T0", "P5-C-T0")))

custom_strips <- strip_nested(background_x = elem_list_rect(fill = c(rep("lightgrey", 2), rep(c("#f2e0bd", "#b2d9b2"),2)) ),
                              by_layer_x = FALSE)

ggplot(data=test_data_df, aes(x=sample, y=COG_counts, fill=COG_anno)) + 
  facet_nested(~ method + land_use, strip = custom_strips, scales="free_x") +
  facetted_pos_scales(x=scales) +
  geom_bar(stat="identity", position="fill", color="white") +
  guides(fill=guide_legend(title = "COG Category", ncol = 4)) +
  scale_fill_manual(values = col_COG) +
  theme(legend.position = "bottom",
        legend.text = element_text(size=6),
        strip.text = element_text(size=12),
        axis.text.x = element_text(size=12))
```

Profiling COGs abundances regarding to the method and land use
```{r}
aggregate(count_COG_MGS$counts, by = list(COG_anno = count_COG_MGS$annotation,
                                          sample = count_COG_MGS$sample), FUN = sum) -> count_COG_MGS
count_COG_MGS$COG_counts = count_COG_MGS$x
for (samp in append(crop,grass)){
  count_COG_MGS[count_COG_MGS$sample  == samp,"total_sample"] = sum(count_COG_MGS[count_COG_MGS$sample == samp,"COG_counts"])
}
count_COG_MGS$per_counts = (count_COG_MGS$COG_counts / count_COG_MGS$total_sample*100)
count_COG_MGS$method = "MGS"
```

```{r}
aggregate(count_COG_P2$counts, by = list(COG_anno = count_COG_P2$annotation,
                                          sample = count_COG_P2$sample), FUN = sum) -> count_COG_P2
count_COG_P2$COG_counts = count_COG_P2$x
for (samp in append(crop,grass)){
  count_COG_P2[count_COG_P2$sample  == samp,"total_sample"] = sum(count_COG_P2[count_COG_P2$sample == samp,"COG_counts"])
}
count_COG_P2$per_counts = (count_COG_P2$COG_counts / count_COG_P2$total_sample*100)
count_COG_P2$method = "P2"
```

```{r}
data_df = rbind(count_COG_MGS, count_COG_P2)
data_df$COG_anno = as.factor(data_df$COG_anno)
data_df$method = as.factor(data_df$method)
data_df$sample = as.character(data_df$sample)
keep_COG = data_df[data_df$per_counts > 1,"COG_anno"]
data_df[startsWith(data_df$sample, "C"), "land_use"] <- "cropland"
data_df[startsWith(data_df$sample, "P"), "land_use"] <- "grassland"
data_df[str_detect(data_df$sample, "-C-"), "treatment"] <- "control"
data_df[str_detect(data_df$sample, "-R-"), "treatment"] <- "amended"
data_df[endsWith(data_df$sample, "0"), "time"] <- "0"
data_df[endsWith(data_df$sample, "1"), "time"] <- "3"
data_df[endsWith(data_df$sample, "4"), "time"] <- "51"
data_df[endsWith(data_df$sample, "6"), "time"] <- "125"
data_df$time <- factor(data_df$time, levels=c("0", "3", "51", "125"))
test_data_df = data_df[data_df$COG_anno %in% keep_COG,]
#color for COG and strips
col_COG = c("J:[Translation, ribosomal structure and biogenesis]" = "#ff0000", 
"A:[RNA processing and modification]" = "#c2af58", "K:[Transcription]" = "#ff9900", 
"L:[Replication, recombination and repair]" = "#ffff00", "B:[Chromatin structure and dynamics]" = "#ffc600", 
"D:[Cell cycle control, cell division, chromosome partitioning]" = "#99ff00", 
"Y:[Nuclear structure]" = "#493126", "V:[Defense mechanisms]" = "#ff008a", 
"T:[Signal transduction mechanisms]" = "#0000ff", "M:[Cell wall/membrane/envelope biogenesis]" = "#9ec928", 
"N:[Cell motility]" = "#006633", "Z:[Cytoskeleton]" = "#660099", 
"W:[Extracellular structures]" = "#336699", "U:[Intracellular trafficking, secretion, and vesicular transport]" = "#33cc99", 
"O:[Posttranslational modification, protein turnover, chaperones]" = "#00ffff", 
"X:[Mobilome: prophages, transposons]" = "#9900ff", "C:[Energy production and conversion]" = "#805642", 
"G:[Carbohydrate transport and metabolism]" = "#ff00ff", "E:[Amino acid transport and metabolism]" = "#99334d", 
"F:[Nucleotide transport and metabolism]" = "#727dcc", "H:[Coenzyme transport and metabolism]" = "#5c5a1b", 
"I:[Lipid transport and metabolism]" = "#0099ff", "P:[Inorganic ion transport and metabolism]" = "#ffcc99", 
"Q:[Secondary metabolites biosynthesis, transport and catabolism]" = "#ff9999", 
"R:[General function prediction only]" = "#d6aadf", "S:[Function unknown]" = "#FFFFFF")

scales <- list(scale_x_discrete(labels=c("T0", "T0", "T0")),
               scale_x_discrete(labels=c("T3", "T3", "T3")),
               scale_x_discrete(labels=c("T51", "T51", "T51")),
               scale_x_discrete(labels=c("T125", "T125", "T125")),
              scale_x_discrete(labels=c("T0", "T0", "T0")),
               scale_x_discrete(labels=c("T3", "T3", "T3")),
               scale_x_discrete(labels=c("T51", "T51", "T51")),
               scale_x_discrete(labels=c("T125", "T125", "T125")),
              scale_x_discrete(labels=c("T0", "T0", "T0")),
               scale_x_discrete(labels=c("T3", "T3", "T3")),
               scale_x_discrete(labels=c("T51", "T51", "T51")),
               scale_x_discrete(labels=c("T125", "T125", "T125")),
               scale_x_discrete(labels=c("T0", "T0", "T0")),
               scale_x_discrete(labels=c("T3", "T3", "T3")),
               scale_x_discrete(labels=c("T51", "T51", "T51")),
               scale_x_discrete(labels=c("T125", "T125", "T125")),
               scale_x_discrete(labels=c("T0", "T0", "T0")),
               scale_x_discrete(labels=c("T3", "T3", "T3")),
               scale_x_discrete(labels=c("T51", "T51", "T51")),
               scale_x_discrete(labels=c("T125", "T125", "T125")),
               scale_x_discrete(labels=c("T0", "T0", "T0")),
               scale_x_discrete(labels=c("T3", "T3", "T3")),
               scale_x_discrete(labels=c("T51", "T51", "T51")),
               scale_x_discrete(labels=c("T125", "T125", "T125")),
               scale_x_discrete(labels=c("T0", "T0", "T0")),
               scale_x_discrete(labels=c("T3", "T3", "T3")),
               scale_x_discrete(labels=c("T51", "T51", "T51")),
               scale_x_discrete(labels=c("T125", "T125", "T125")),
               scale_x_discrete(labels=c("T0", "T0", "T0")),
               scale_x_discrete(labels=c("T3", "T3", "T3")),
               scale_x_discrete(labels=c("T51", "T51", "T51")),
               scale_x_discrete(labels=c("T125", "T125", "T125")))

custom_strips <- strip_nested(background_x = elem_list_rect(fill = c(rep("lightgrey", 2),
                                                                     rep(c("#f2e0bd", "#b2d9b2"), 2),
                                                                     rep(c("#fbbb3f", "#f2e0bd", "#2abf2a", "#b2d9b2"),2),
                                                                     rep(c("white"), 48))),
                              by_layer_x = FALSE)

ggplot(data=test_data_df, aes(x=sample, y=COG_counts, fill=COG_anno)) + 
  facet_nested(~ method + land_use + treatment + time, strip = custom_strips, scales="free_x") +
  facetted_pos_scales(x=scales) +
  geom_bar(stat="identity", position="fill", color="white") +
  guides(fill=guide_legend(title = "COG Category", ncol = 4)) +
  scale_fill_manual(values = col_COG) +
  theme(legend.position = "bottom",
        legend.text = element_text(size=6),
        strip.text = element_text(size=12),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) -> plot_COG_bar
ggsave (plot = plot_COG_bar, filename = "Output/COG_barplot.png", width = 10, height = 8, dpi = 200)
```
On filtre les COGs significatifs => relevé des variations intergroupes
```{r}
count_COG_MGS = filter(count_COG_MGS, COG %in% DA_COG_MGS)
aggregate(count_COG_MGS[1:48], by = list(COG_anno = count_COG_MGS$annotation), FUN = sum) -> count_COG_MGS
rownames(count_COG_MGS) = count_COG_MGS$COG_anno
count_COG_MGS = count_COG_MGS[,-1]
res4_df <- data.frame( baseMean=numeric(), 
                        log2FoldChange=numeric(), 
                        lfcSE=numeric(), 
                        stat=numeric(), 
                        pvalue=numeric(), 
                        padj=numeric(),
                        conditions = factor(),
                        COG = character())
count_COG_MGS = as.data.frame(count_COG_MGS)
for ( dataset in c("grass_0", "grass_3", "grass_51", "grass_125")){
  counts_matrix <- as.matrix(count_COG_MGS[,get(dataset)],rownames = TRUE)
  sample_data <- meta[get(dataset),,drop=FALSE]
  res <- DESeqDataSetFromMatrix(countData = counts_matrix,
                                  colData = sample_data,
                                  design = ~ wheat_straw_amendment, tidy = FALSE)
 res <- DESeq(res, parallel = TRUE)
 res_1 = results(res, parallel = TRUE)
  res_2 = as.data.frame((res_1))
  res_2$COG = rownames(res_2)
  res_2$conditions = as.factor(rep(dataset, nrow(res_2)))
  res4_df <- bind_rows(res4_df, res_2)
}
rownames(res4_df) = NULL
res4_df = filter(res4_df, padj < 0.01 & abs(log2FoldChange) > 0.25)
res4_df = res4_df[order(res4_df$log2FoldChange, decreasing = TRUE),]
```

```{r}
a = read_delim("Output/DA_COG_MGS.tsv", delim = "\t")
b = read_delim("Output/DA_COG_P2.tsv", delim = "\t")
a = as.data.frame (a)
b = as.data.frame (b)
length(intersect(a[a$cluster == 5,"COG_number"], b[b$cluster == 1,"COG_number"]))
```
