---
title: "Joinction P2 Sample ID"
auteur: "Dinh-Phuc Hoang"
date: "2025-03-31"
---
Loading the libraries
```{r}
library(readr)
library(dplyr)
library(tidyverse)
```
Loading the data
```{r}
COG_anno = read_delim("description_mapfiles/COG_cat.txt",delim = "\t",col_names = FALSE)
COG_cat_anno = read_delim("description_mapfiles/translate_COG_cat_anno.txt",delim = "\t",col_names = FALSE)
COG_cat_anno = as.data.frame(COG_cat_anno)
COG_anno = as.data.frame(COG_anno)
rownames(COG_anno) = COG_anno[,1]
COG_anno = COG_anno[,-1]
names(COG_anno) = c("COG_letter","COG_description")
names(COG_cat_anno) = c("COG_letter","COG_category")
COG_anno$COG_letter = substr(COG_anno$COG_letter, 1, 1)
COG_anno = dplyr::select(COG_anno,COG_letter,COG_description)
COG_anno_cat = left_join(COG_anno,COG_cat_anno,by = "COG_letter")
rownames(COG_anno_cat) = rownames(COG_anno)
write_rds(COG_anno_cat,"description_mapfiles/COG_anno.rds")
```

```{r}
COG_cat_anno$text = paste0(COG_cat_anno$COG_letter,":[",COG_cat_anno$COG_category,"]")
color = c("#ff0000","#c2af58","#ff9900","#ffff00",
"#ffc600",
"#99ff00",
"#493126",
"#ff008a",
"#0000ff",
"#9ec928",
"#006633",
"#660099",
"#336699",
"#33cc99",
"#00ffff",
"#9900ff",
"#805642",
"#ff00ff",
"#99334d",
"#727dcc",
"#5c5a1b",
"#0099ff",
"#ffcc99",
"#ff9999",
"#d6aadf")
a = c(COG_cat_anno$text)
names(a) = color
```